; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = mbed
lib_deps =  
    mbed-wiznet/WIZnet_Library @ 0.0.0+sha.cb8808b47e69 ; WIZnet_Library
    mbed-ethernetinterfacew5500-makers/W5500Interface @ 0.0.0+sha.5499fa2d8898  ; W5500 Library

    ; RECOMMENDED
    ; Accept new functionality in a backwards compatible manner and patches
    ; mbed-ethernetinterfacew5500-makers/W5500Interface @ ^0.0.0+sha.5499fa2d8898
    ; http://os.mbed.com/teams/EthernetInterfaceW5500-makers/code/W5500Interface/
    ; http://os.mbed.com/teams/mbed_example/code/WebSocketClient/
    ; http://os.mbed.com/teams/WIZnet/code/WIZnetInterface/
