; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8_128k]
platform = ststm32
board = bluepill_f103c8_128k
borad_build.core = STM32Duino
framework = arduino

build_type = debug
build_flags =
    -fexceptions    ; Enable exception handling
build_unflags =
    -fno-exceptions ; Disable the blocking of exceptionsð

debug_init_break = tbreak setup

debug_tool = stlink
upload_protocol = stlink